export const BLIND_BID_VAULT_ADDRESS = "0xe582DAa8293b664c74BfC29ADd2c47eB96471b2b" as const;

export const BLIND_BID_VAULT_ABI = [
  {"type":"constructor","inputs":[{"name":"_token","type":"address","internalType":"contract IERC20"},{"name":"_priceWeight","type":"uint256","internalType":"uint256"},{"name":"_qualityWeight","type":"uint256","internalType":"uint256"}],"stateMutability":"nonpayable"},
  {"type":"function","name":"AUDITOR_ROLE","inputs":[],"outputs":[{"name":"","type":"bytes32","internalType":"bytes32"}],"stateMutability":"view"},
  {"type":"function","name":"DEFAULT_ADMIN_ROLE","inputs":[],"outputs":[{"name":"","type":"bytes32","internalType":"bytes32"}],"stateMutability":"view"},
  {"type":"function","name":"auctions","inputs":[{"name":"","type":"uint256","internalType":"uint256"}],"outputs":[{"name":"organizer","type":"address","internalType":"address"},{"name":"treasury","type":"address","internalType":"address"},{"name":"stakeAmount","type":"uint256","internalType":"uint256"},{"name":"minPrice","type":"uint256","internalType":"uint256"},{"name":"maxPrice","type":"uint256","internalType":"uint256"},{"name":"commitEnd","type":"uint256","internalType":"uint256"},{"name":"revealEnd","type":"uint256","internalType":"uint256"},{"name":"state","type":"uint8","internalType":"enum BlindBidVault.AuctionState"},{"name":"winner","type":"address","internalType":"address"},{"name":"winningPrice","type":"uint256","internalType":"uint256"}],"stateMutability":"view"},
  {"type":"function","name":"auditScores","inputs":[{"name":"","type":"uint256","internalType":"uint256"},{"name":"","type":"address","internalType":"address"}],"outputs":[{"name":"","type":"uint256","internalType":"uint256"}],"stateMutability":"view"},
  {"type":"function","name":"cancelAuction","inputs":[{"name":"auctionId","type":"uint256","internalType":"uint256"}],"outputs":[],"stateMutability":"nonpayable"},
  {"type":"function","name":"claimRefund","inputs":[{"name":"auctionId","type":"uint256","internalType":"uint256"}],"outputs":[],"stateMutability":"nonpayable"},
  {"type":"function","name":"commitBid","inputs":[{"name":"auctionId","type":"uint256","internalType":"uint256"},{"name":"commitment","type":"bytes32","internalType":"bytes32"}],"outputs":[],"stateMutability":"nonpayable"},
  {"type":"function","name":"commitments","inputs":[{"name":"","type":"uint256","internalType":"uint256"},{"name":"","type":"address","internalType":"address"}],"outputs":[{"name":"hash","type":"bytes32","internalType":"bytes32"},{"name":"revealed","type":"bool","internalType":"bool"},{"name":"slashed","type":"bool","internalType":"bool"},{"name":"refunded","type":"bool","internalType":"bool"},{"name":"price","type":"uint256","internalType":"uint256"}],"stateMutability":"view"},
  {"type":"function","name":"createAuction","inputs":[{"name":"treasury","type":"address","internalType":"address"},{"name":"stakeAmount","type":"uint256","internalType":"uint256"},{"name":"minPrice","type":"uint256","internalType":"uint256"},{"name":"maxPrice","type":"uint256","internalType":"uint256"},{"name":"commitEnd","type":"uint256","internalType":"uint256"},{"name":"revealEnd","type":"uint256","internalType":"uint256"}],"outputs":[{"name":"auctionId","type":"uint256","internalType":"uint256"}],"stateMutability":"nonpayable"},
  {"type":"function","name":"getRoleAdmin","inputs":[{"name":"role","type":"bytes32","internalType":"bytes32"}],"outputs":[{"name":"","type":"bytes32","internalType":"bytes32"}],"stateMutability":"view"},
  {"type":"function","name":"grantRole","inputs":[{"name":"role","type":"bytes32","internalType":"bytes32"},{"name":"account","type":"address","internalType":"address"}],"outputs":[],"stateMutability":"nonpayable"},
  {"type":"function","name":"hasCommitted","inputs":[{"name":"","type":"uint256","internalType":"uint256"},{"name":"","type":"address","internalType":"address"}],"outputs":[{"name":"","type":"bool","internalType":"bool"}],"stateMutability":"view"},
  {"type":"function","name":"hasRole","inputs":[{"name":"role","type":"bytes32","internalType":"bytes32"},{"name":"account","type":"address","internalType":"address"}],"outputs":[{"name":"","type":"bool","internalType":"bool"}],"stateMutability":"view"},
  {"type":"function","name":"nextAuctionId","inputs":[],"outputs":[{"name":"","type":"uint256","internalType":"uint256"}],"stateMutability":"view"},
  {"type":"function","name":"priceWeight","inputs":[],"outputs":[{"name":"","type":"uint256","internalType":"uint256"}],"stateMutability":"view"},
  {"type":"function","name":"qualityWeight","inputs":[],"outputs":[{"name":"","type":"uint256","internalType":"uint256"}],"stateMutability":"view"},
  {"type":"function","name":"renounceRole","inputs":[{"name":"role","type":"bytes32","internalType":"bytes32"},{"name":"callerConfirmation","type":"address","internalType":"address"}],"outputs":[],"stateMutability":"nonpayable"},
  {"type":"function","name":"revealBid","inputs":[{"name":"auctionId_","type":"uint256","internalType":"uint256"},{"name":"bidder","type":"address","internalType":"address"},{"name":"price","type":"uint256","internalType":"uint256"},{"name":"secret","type":"string","internalType":"string"}],"outputs":[],"stateMutability":"nonpayable"},
  {"type":"function","name":"revokeRole","inputs":[{"name":"role","type":"bytes32","internalType":"bytes32"},{"name":"account","type":"address","internalType":"address"}],"outputs":[],"stateMutability":"nonpayable"},
  {"type":"function","name":"setAuditScore","inputs":[{"name":"auctionId","type":"uint256","internalType":"uint256"},{"name":"bidder","type":"address","internalType":"address"},{"name":"aiScore","type":"uint256","internalType":"uint256"},{"name":"docHash","type":"bytes32","internalType":"bytes32"},{"name":"summaryUri","type":"string","internalType":"string"}],"outputs":[],"stateMutability":"nonpayable"},
  {"type":"function","name":"settleAuction","inputs":[{"name":"auctionId","type":"uint256","internalType":"uint256"}],"outputs":[],"stateMutability":"nonpayable"},
  {"type":"function","name":"slashBid","inputs":[{"name":"auctionId","type":"uint256","internalType":"uint256"},{"name":"bidder","type":"address","internalType":"address"}],"outputs":[],"stateMutability":"nonpayable"},
  {"type":"function","name":"supportsInterface","inputs":[{"name":"interfaceId","type":"bytes4","internalType":"bytes4"}],"outputs":[{"name":"","type":"bool","internalType":"bool"}],"stateMutability":"view"},
  {"type":"function","name":"token","inputs":[],"outputs":[{"name":"","type":"address","internalType":"contract IERC20"}],"stateMutability":"view"},
  {"type":"event","name":"AuctionCancelled","inputs":[{"name":"auctionId","type":"uint256","indexed":true,"internalType":"uint256"}],"anonymous":false},
  {"type":"event","name":"AuctionCreated","inputs":[{"name":"auctionId","type":"uint256","indexed":true,"internalType":"uint256"},{"name":"organizer","type":"address","indexed":true,"internalType":"address"},{"name":"treasury","type":"address","indexed":false,"internalType":"address"},{"name":"stakeAmount","type":"uint256","indexed":false,"internalType":"uint256"},{"name":"minPrice","type":"uint256","indexed":false,"internalType":"uint256"},{"name":"maxPrice","type":"uint256","indexed":false,"internalType":"uint256"},{"name":"commitEnd","type":"uint256","indexed":false,"internalType":"uint256"},{"name":"revealEnd","type":"uint256","indexed":false,"internalType":"uint256"}],"anonymous":false},
  {"type":"event","name":"AuctionSettled","inputs":[{"name":"auctionId","type":"uint256","indexed":true,"internalType":"uint256"},{"name":"winner","type":"address","indexed":true,"internalType":"address"},{"name":"winningPrice","type":"uint256","indexed":false,"internalType":"uint256"}],"anonymous":false},
  {"type":"event","name":"AuditScoreSet","inputs":[{"name":"auctionId","type":"uint256","indexed":true,"internalType":"uint256"},{"name":"bidder","type":"address","indexed":true,"internalType":"address"},{"name":"aiScore","type":"uint256","indexed":false,"internalType":"uint256"},{"name":"docHash","type":"bytes32","indexed":false,"internalType":"bytes32"},{"name":"summaryUri","type":"string","indexed":false,"internalType":"string"}],"anonymous":false},
  {"type":"event","name":"BidCommitted","inputs":[{"name":"auctionId","type":"uint256","indexed":true,"internalType":"uint256"},{"name":"bidder","type":"address","indexed":true,"internalType":"address"},{"name":"commitment","type":"bytes32","indexed":false,"internalType":"bytes32"}],"anonymous":false},
  {"type":"event","name":"BidRevealed","inputs":[{"name":"auctionId","type":"uint256","indexed":true,"internalType":"uint256"},{"name":"bidder","type":"address","indexed":true,"internalType":"address"},{"name":"price","type":"uint256","indexed":false,"internalType":"uint256"}],"anonymous":false},
  {"type":"event","name":"BidSlashed","inputs":[{"name":"auctionId","type":"uint256","indexed":true,"internalType":"uint256"},{"name":"bidder","type":"address","indexed":true,"internalType":"address"},{"name":"amount","type":"uint256","indexed":false,"internalType":"uint256"},{"name":"treasury","type":"address","indexed":false,"internalType":"address"}],"anonymous":false},
  {"type":"event","name":"RoleAdminChanged","inputs":[{"name":"role","type":"bytes32","indexed":true,"internalType":"bytes32"},{"name":"previousAdminRole","type":"bytes32","indexed":true,"internalType":"bytes32"},{"name":"newAdminRole","type":"bytes32","indexed":true,"internalType":"bytes32"}],"anonymous":false},
  {"type":"event","name":"RoleGranted","inputs":[{"name":"role","type":"bytes32","indexed":true,"internalType":"bytes32"},{"name":"account","type":"address","indexed":true,"internalType":"address"},{"name":"sender","type":"address","indexed":true,"internalType":"address"}],"anonymous":false},
  {"type":"event","name":"RoleRevoked","inputs":[{"name":"role","type":"bytes32","indexed":true,"internalType":"bytes32"},{"name":"account","type":"address","indexed":true,"internalType":"address"},{"name":"sender","type":"address","indexed":true,"internalType":"address"}],"anonymous":false},
  {"type":"event","name":"StakeRefunded","inputs":[{"name":"auctionId","type":"uint256","indexed":true,"internalType":"uint256"},{"name":"bidder","type":"address","indexed":true,"internalType":"address"},{"name":"amount","type":"uint256","indexed":false,"internalType":"uint256"}],"anonymous":false},
  {"type":"error","name":"AccessControlBadConfirmation","inputs":[]},
  {"type":"error","name":"AccessControlUnauthorizedAccount","inputs":[{"name":"account","type":"address","internalType":"address"},{"name":"neededRole","type":"bytes32","internalType":"bytes32"}]},
  {"type":"error","name":"AlreadyCancelled","inputs":[]},
  {"type":"error","name":"AlreadyCommitted","inputs":[]},
  {"type":"error","name":"AlreadyRefunded","inputs":[]},
  {"type":"error","name":"AlreadyRevealed","inputs":[]},
  {"type":"error","name":"AlreadySettled","inputs":[]},
  {"type":"error","name":"AlreadySlashed","inputs":[]},
  {"type":"error","name":"AuctionClosed","inputs":[]},
  {"type":"error","name":"AuctionNotFound","inputs":[]},
  {"type":"error","name":"InvalidAmount","inputs":[]},
  {"type":"error","name":"InvalidPrice","inputs":[]},
  {"type":"error","name":"InvalidReveal","inputs":[]},
  {"type":"error","name":"InvalidScore","inputs":[]},
  {"type":"error","name":"InvalidTiming","inputs":[]},
  {"type":"error","name":"InvalidWeights","inputs":[]},
  {"type":"error","name":"NotCommitted","inputs":[]},
  {"type":"error","name":"NotOrganizer","inputs":[]},
  {"type":"error","name":"PriceOutOfBounds","inputs":[]},
  {"type":"error","name":"ReentrancyGuardReentrantCall","inputs":[]},
  {"type":"error","name":"RevealNotOpen","inputs":[]},
  {"type":"error","name":"SafeERC20FailedOperation","inputs":[{"name":"token","type":"address","internalType":"address"}]}
] as const;